print("Let's play Silly Sentences!")
name = input("Enter a name: ")
adj1 = input("Enter an adjective: ")
adj2 = input("Enter an adjective: ")
advb = input("Enter an adverb: ")
fod1 = input("Enter a food: ")
fod2 = input("Enter another food: ")
noun = input("Enter a noun: ")
loca = input("Enter a place: ")
verb = input("Enter a verb: ")
print(name + " was planning a dream vacation to " + loca)
print(name + " was especially looking forward to trying the local cuisine, including " + adj1 + " " + fod1 + " and " + fod2 + ".")
print(name + " will have to practice the language " + advb + " to make it easier to " + verb + " with people.")
print(name + " has a long list of sights to see, including the " + noun + " museum and the " + adj2 + " park.")